name: um_test
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  go_router: ^13.0.1
  cupertino_icons: ^1.0.8
  google_maps_flutter: ^2.5.3
  location: ^5.0.3
  http: ^1.4.0
  flutter_dotenv: ^5.2.1
  uuid: ^4.5.1
  image_gallery_saver_plus: ^4.0.1
  permission_handler: ^11.3.0
  path_provider: ^2.1.2
  share_plus: ^7.2.1
  intl: ^0.18.1
  device_info_plus: ^10.0.1
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/bike_stations.json
    - .env
    - assets/landmarks.json
    - assets/images/eum_logo.png
    - assets/images/reward_unlocked.png
    - assets/images/reward_locked.png
    - assets/images/reward_header.png
    - assets/images/onboarding1.png
    - assets/images/onboarding2.png
    - assets/images/onboarding3.png

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/icon.png"
